import { mkdir, rm, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";

const GOOGLE_FONTS_CSS_BASE = "https://fonts.googleapis.com/css2";
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const fontFamilies = [
  {
    family: "Noto Sans TC",
    query: "Noto+Sans+TC:wght@400..700",
    directory: "noto-sans-tc",
  },
  {
    family: "Noto Serif TC",
    query: "Noto+Serif+TC:wght@700",
    directory: "noto-serif-tc",
  },
] as const;

const fetchResource = async (url: string) => {
  const response = await fetch(url, { headers: { "User-Agent": USER_AGENT } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText}: ${url}`);
  return response;
};

async function main() {
  const generatedSections: string[] = [
    "/*",
    " * Generated by scripts/update-brand-fonts.ts from the Google Fonts CSS2 API.",
    " * The local unicode-range shards provide complete Noto TC coverage without",
    " * forcing every visitor to download a monolithic CJK font file.",
    " */",
  ];

  for (const definition of fontFamilies) {
    const cssUrl = `${GOOGLE_FONTS_CSS_BASE}?family=${definition.query}&display=swap`;
    const upstreamCss = await (await fetchResource(cssUrl)).text();
    const faces = upstreamCss.match(/@font-face\s*\{[^}]+\}/g);
    if (!faces?.length) throw new Error(`No @font-face blocks returned for ${definition.family}`);

    const outputDirectory = join("public", "fonts", definition.directory);
    await rm(outputDirectory, { recursive: true, force: true });
    await mkdir(outputDirectory, { recursive: true });

    const localFaces: string[] = [];
    for (const [index, face] of faces.entries()) {
      const remoteUrl = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
      if (!remoteUrl) throw new Error(`Missing WOFF2 URL in ${definition.family} face ${index}`);

      const upstreamName = basename(new URL(remoteUrl).pathname);
      const localName = `${String(index).padStart(3, "0")}-${upstreamName}`;
      const fontData = Buffer.from(await (await fetchResource(remoteUrl)).arrayBuffer());
      if (fontData.subarray(0, 4).toString("ascii") !== "wOF2") {
        throw new Error(`Invalid WOFF2 response for ${remoteUrl}`);
      }
      await writeFile(join(outputDirectory, localName), fontData);
      localFaces.push(face.replace(remoteUrl, `/fonts/${definition.directory}/${localName}`));
    }

    generatedSections.push(
      "",
      `/* ${definition.family}; source manifest: ${cssUrl} */`,
      localFaces.join("\n"),
    );
    console.log(`Downloaded ${faces.length} unicode-range shards for ${definition.family}`);
  }

  await writeFile("src/styles/fonts.css", `${generatedSections.join("\n")}\n`, "utf8");
  console.log("Updated src/styles/fonts.css and public/fonts unicode-range assets");
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
